// Autogenerated Portfolio Configuration and Controls
const DEFAULT_CONFIG = {
  hero: {
    name: "Alex Carter",
    role: "Lead Software Engineer & Systems Architect",
    subtitle: "I'm Alex Carter, a Lead Systems Architect and Full Stack Engineer. I build clean, high-performance backends, custom ERPNext/Frappe setups, and robust distributed systems.",
    specialties: "Python / Django, JavaScript / React, Frappe / ERPNext, Node.js / Express, Distributed Systems, Kubernetes / DevOps",
    location: "San Francisco, CA (GMT-7)",
    availability: "Consulting & contract roles (20h/week)",
    learning: "Rust concurrency primitives, WebGPU shaders",
    fun_fact: "Can compile Linux kernels from scratch and roast coffee beans at 220°C",
    bio: "I am a software engineer with over 7 years of professional experience writing code, configuring cloud networks, and optimizing relational databases. I believe that writing code is only 30% of the job; the other 70% is understanding business requirements, architecting systems for growth, and building user-centric interfaces.\n\nMy professional expertise lies in constructing custom integrations on top of the Frappe Framework / ERPNext, building high-throughput REST APIs in Python (Django / FastAPI), and orchestrating containers in production environments using Kubernetes (EKS/GKE)."
  },
  experience: [
    {
      title: "Lead Systems Architect",
      company: "Apex Tech Systems",
      period: "Jan 2024 - Present",
      summary: "Architecting distributed ERP integrations and auto-scaling API pipelines to handle peak seasonal traffic spikes.",
      achievements: [
        "Designed custom Frappe stock-reconciliation pipeline reducing locking conflicts by 92%.",
        "Orchestrated migration from VM-based workloads to Kubernetes, decreasing cloud compute costs by 35%.",
        "Mentored a team of 6 engineers on database optimization, clean code practices, and unit test automation."
      ],
      tags: "Frappe, MariaDB, Redis, AWS EKS, Docker"
    },
    {
      title: "Senior Software Engineer",
      company: "CloudScale Labs",
      period: "Jun 2021 - Dec 2023",
      summary: "Owned the API services group responsible for processing high-velocity event tracking data.",
      achievements: [
        "Built a telemetry ingestion service in Go that handles 50,000+ API requests per second with less than 2ms response latency.",
        "Optimized Django Rest Framework serializations, reducing query count (N+1 queries) by 60%.",
        "Integrated continuous deployment pipelines using GitHub Actions and Helm charts for zero-downtime updates."
      ],
      tags: "Go, Python, Django, PostgreSQL, Grafana"
    },
    {
      title: "Software Developer",
      company: "DevCore Integration Group",
      period: "Mar 2019 - May 2021",
      summary: "Developed full-stack web products and integrated external third-party payment and supply APIs.",
      achievements: [
        "Designed dynamic frontend dashboards in React, reducing load time from 4.2 seconds to 1.1 seconds.",
        "Wrote complex Celery task schedulers for bulk email notification delivery and report generation.",
        "Maintained and extended legacy MariaDB database tables, writing custom SQL migration patches."
      ],
      tags: "React, Node.js, PostgreSQL, Celery, Redis"
    }
  ],
  skills: {
    languages: [
      { name: "Python", value: 95 },
      { name: "JavaScript / TypeScript", value: 90 },
      { name: "Go (Golang)", value: 80 },
      { name: "SQL (MariaDB/Postgres)", value: 92 }
    ],
    frameworks: [
      { name: "Frappe / ERPNext", value: 95 },
      { name: "Django / FastAPI", value: 90 },
      { name: "React / Next.js", value: 85 },
      { name: "Node.js (Express)", value: 80 }
    ],
    cloud: [
      { name: "Docker / Kubernetes", value: 88 },
      { name: "AWS (ECS/EKS/RDS/S3)", value: 85 },
      { name: "Terraform / IaC", value: 78 },
      { name: "GitHub Actions CI/CD", value: 90 }
    ]
  },
  projects: {
    "nexis-erp": {
      id: "nexis-erp",
      title: "Nexis ERP Custom Integration",
      category: "ERPNext / Frappe",
      summary: "High-throughput API sync engine for ERPNext that optimizes MariaDB query execution and reduces sync time by 85% for large-scale retail systems.",
      thumbnail: "assets/images/nexis_erp_thumbnail.png",
      featured: true,
      status: "Production",
      github_stars: 42,
      metrics: {
        users: "15,000+ Daily",
        performance: "85% Sync Speedup",
        latency: "< 120ms API response",
        business_impact: "Saved $120k/yr in infrastructure costs"
      },
      case_study: {
        timeline: "3 Months (Q1 2026)",
        client: "Apex Retail Group",
        team_size: "3 Engineers",
        role: "Lead Systems Architect",
        live_demo: "#",
        github_repo: "https://github.com/developer/nexis-erp-sync",
        problem: "Apex Retail Group had over 100 outlets syncing inventory data to a centralized ERPNext server. Due to MariaDB lock contention and unindexed search queries, sync operations took up to 45 seconds, causing timeouts, duplicate transactions, and severe checkout delays.",
        requirements: "Reduce synchronization latency to under 3 seconds, eliminate MariaDB deadlocks, support offline synchronization, and build a robust transaction audit trail.",
        challenges: "1. Frappe's default ORM (`Document.save`) was too slow for bulk operations (over 10,000 items).\n2. Real-time stock validations triggered circular hooks that caused database lock escalations.\n3. Weak network conditions at remote checkout terminals led to half-completed sync requests.",
        solution: "We bypassed the standard ORM for high-frequency writes by implementing a custom PyPika query builder pipeline combined with a Redis-backed queue system (RQ). We added an optimistic locking mechanism on inventory quantities and built a transactional middleware to ensure atomic rollbacks.",
        results: "Inventory synchronization was reduced from 45 seconds to 1.8 seconds. MariaDB database utilization dropped from 94% to 22% under peak load, and double-entry synchronization bugs were entirely resolved.",
        architecture: {
          frontend: "Vite + Tailwind CSS (Custom ERP Portal)",
          backend: "Frappe Framework (v15) & Python",
          database: "MariaDB with Redis caching layer"
        },
        tech_stack: {
          frontend: ["React", "TypeScript", "TailwindCSS"],
          backend: ["Python", "Frappe", "Redis", "RQ"],
          cloud_devops: ["AWS ECS", "Docker", "Terraform"]
        },
        code_snippet: `import frappe
from pypika import Table, Query

@frappe.whitelist()
def bulk_sync_inventory(items):
    """
    High-performance bulk synchronization bypassing the standard Frappe ORM
    using PyPika query builder and raw MariaDB bulk insert.
    """
    if not items: return {"status": "success", "synced": 0}
    frappe.has_permission("Stock Ledger Entry", throw=True)
    
    sle = Table("tabStock Ledger Entry")
    query = Query.into(sle).columns(
        "name", "item_code", "warehouse", "actual_qty", "posting_date", "posting_time"
    )
    
    for item in items:
        uid = frappe.generate_hash(length=10)
        query = query.insert(
            f"SLE-{uid}", item.get("item_code"), item.get("warehouse"),
            item.get("qty"), frappe.utils.nowdate(), frappe.utils.nowtime()
        )
        
    try:
        frappe.db.sql(str(query), as_dict=False)
        frappe.cache().delete_value("stock_balance_cache")
        frappe.db.commit()
        return {"status": "success", "synced": len(items)}
    except Exception as e:
        frappe.db.rollback()
        frappe.log_error(message=str(e), title="Bulk Sync Failed")
        frappe.throw("Bulk synchronization aborted due to database transaction failure.")`,
        metrics_cards: {
          lighthouse: "98/100",
          load_time: "1.2s",
          api_latency: "85ms average"
        }
      }
    },
    "aether-db": {
      id: "aether-db",
      title: "AetherDB: Distributed Key-Value Store",
      category: "Backend Systems",
      summary: "Lightweight, highly available distributed key-value store utilizing the Raft consensus protocol for guaranteed state consistency across distributed clusters.",
      thumbnail: "assets/images/aether_db_thumbnail.png",
      featured: true,
      status: "Active Development",
      github_stars: 284,
      metrics: {
        users: "2,400+ GitHub Stars",
        performance: "50,000 req/sec writes",
        latency: "< 2ms read latency",
        business_impact: "Zero split-brain occurrences"
      },
      case_study: {
        timeline: "6 Months (Q3-Q4 2025)",
        client: "Open Source Community",
        team_size: "Solo Project",
        role: "Creator & Core Maintainer",
        live_demo: "#",
        github_repo: "https://github.com/developer/aetherdb",
        problem: "Existing distributed configurations either relied heavily on ZooKeeper or suffered from consistency bugs during network partitions (split-brain). I wanted to create a developer-friendly key-value store.",
        requirements: "Strict linearizable reads, fault tolerance, dynamic membership, and snapshotting.",
        challenges: "1. Managing term elections.\n2. Implementing compaction.\n3. Custom TCP serialization.",
        solution: "Built a custom Raft implementation in Go. Utilized Protocol Buffers and copy-on-write memory snapshots.",
        results: "AetherDB handles up to 50k write operations per second, with cluster quorum recovery in less than 150ms.",
        architecture: {
          frontend: "React-based health dashboard",
          backend: "Go (Golang) Raft Core Engine",
          database: "LSM-Tree local storage engine"
        },
        tech_stack: {
          frontend: ["React", "Chart.js"],
          backend: ["Go", "gRPC", "Protobuf"],
          cloud_devops: ["Kubernetes", "Docker", "Helm"]
        },
        code_snippet: `package main

import (
	"sync"
)

type NodeRole int
const (
	Follower NodeRole = iota
	Candidate
	Leader
)

type RaftNode struct {
	mu          sync.Mutex
	id          int
	currentTerm int
	votedFor    int
	role        NodeRole
}

func (rn *RaftNode) startElection() {
	rn.mu.Lock()
	rn.role = Candidate
	rn.currentTerm++
	rn.votedFor = rn.id
	rn.mu.Unlock()

	votesReceived := 1
	for _, peer := range rn.getPeers() {
		go func(p Peer) {
			args := RequestVoteArgs{Term: rn.currentTerm, CandidateId: rn.id}
			reply := RequestVoteReply{}
			if rn.sendRequestVote(p, &args, &reply) {
				rn.mu.Lock()
				defer rn.mu.Unlock()
				if reply.VoteGranted && rn.role == Candidate {
					votesReceived++
					if votesReceived > (len(rn.getPeers())+1)/2 {
						rn.role = Leader
						rn.startHeartbeats()
					}
				}
			}
		}(peer)
	}
}`,
        metrics_cards: {
          lighthouse: "N/A (CLI)",
          load_time: "< 10ms startup",
          api_latency: "< 2ms API operations"
        }
      }
    },
    "synthanalyze": {
      id: "synthanalyze",
      title: "SynthAnalytics SaaS Dashboard",
      category: "Web Applications",
      summary: "Real-time analytics engine and dashboard visualizing user conversion funnels, event stream latency, and live server health metrics via WebSockets.",
      thumbnail: "assets/images/synthanalyze_thumbnail.png",
      featured: false,
      status: "Production",
      github_stars: 115,
      metrics: {
        users: "8,000+ Active Accounts",
        performance: "Chart rendering < 15ms",
        latency: "50ms WebSocket updates",
        business_impact: "Increased conversion by 14%"
      },
      case_study: {
        timeline: "4 Months (Q2 2025)",
        client: "SynthSaaS Inc.",
        team_size: "2 Engineers",
        role: "Full Stack Engineer",
        live_demo: "#",
        github_repo: "https://github.com/developer/synthanalyze",
        problem: "SynthSaaS needed a dashboard to show their users detailed live metrics of API usage and server request rates. Existing analytics tools suffered from high integration complexity and delayed reporting by up to 5 minutes.",
        requirements: "Sub-second real-time charts, support for multi-tenant custom dashboard layouts, CSV report export, and a clean theme-matching interface.",
        challenges: "1. Visualizing over 100,000 data points in real time on mobile browsers without freezing the browser thread.\n2. Keeping WebSocket connections alive across variable networks.\n3. Managing complex dashboard filters in a centralized frontend state store.",
        solution: "We built the dashboard using React with dynamic canvas-based chart rendering (using custom WebGL elements). We handled WebSocket reconnections using exponential backoff with jitter and stored filter layouts in an immutable URL-synced state store.",
        results: "The dashboard rendered high-volume real-time feeds smoothly at 60fps. Users saw analytical updates within 50 milliseconds of event emission. Lead conversion rates increased by 14% due to the immediate visibility of usage trends.",
        architecture: {
          frontend: "React with Tailwind CSS & Canvas charting",
          backend: "Node.js (Express) with Socket.io server",
          database: "TimescaleDB (PostgreSQL) for time-series analytics"
        },
        tech_stack: {
          frontend: ["React", "Next.js", "Chart.js", "WebSockets"],
          backend: ["Node.js", "Express", "Socket.io"],
          cloud_devops: ["GCP GKE", "Docker", "Terraform"]
        },
        code_snippet: `import React, { useEffect, useRef } from 'react';

export const RealTimeChart = ({ dataPoints }) => {
  const canvasRef = useRef(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    const dpr = window.devicePixelRatio || 1;
    
    canvas.width = canvas.clientWidth * dpr;
    canvas.height = canvas.clientHeight * dpr;
    ctx.scale(dpr, dpr);
    
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.strokeStyle = 'rgba(99, 102, 241, 0.8)';
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    
    const step = canvas.clientWidth / (dataPoints.length - 1);
    dataPoints.forEach((point, index) => {
      const x = index * step;
      const y = canvas.clientHeight - (point.value * canvas.clientHeight);
      if (index === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    });
    ctx.stroke();
  }, [dataPoints]);

  return <canvas ref={canvasRef} className="w-full h-64 bg-slate-900 rounded-lg p-4" />;
};`,
        metrics_cards: {
          lighthouse: "100/100",
          load_time: "0.8s FCP",
          api_latency: "< 30ms REST queries"
        }
      }
    },
    "opsflow": {
      id: "opsflow",
      title: "OpsFlow: Kubernetes Automation Platform",
      category: "DevOps",
      summary: "An infrastructure-as-code automation dashboard orchestrating deployment pipelines, secrets injection, and isolated staging environments.",
      thumbnail: "assets/images/opsflow_thumbnail.png",
      featured: false,
      status: "Maintenance",
      github_stars: 86,
      metrics: {
        users: "18 Dev Teams",
        performance: "Staging sandbox < 90s",
        latency: "Zero downtime builds",
        business_impact: "Reduced deployment times by 60%"
      },
      case_study: {
        timeline: "5 Months (Q4 2025)",
        client: "Internal Infrastructure team",
        team_size: "2 Engineers",
        role: "Senior Infrastructure Engineer",
        live_demo: "#",
        github_repo: "https://github.com/developer/opsflow",
        problem: "Engineers had to wait for hours to get automated staging environments to test branches. Cloud resources were left running indefinitely, inflating hosting bills by 40%.",
        requirements: "Automated deployment of sandbox staging clusters on git branch push, automatic clean-up of idle environments, and encrypted secrets storage.",
        challenges: "1. Dynamically creating DNS records and certificates without rate-limit blockages.\n2. Securing cluster access tokens.\n3. Monitoring cluster RAM and CPU metrics dynamically.",
        solution: "We wrote a custom Kubernetes operator in Go that monitors git branch Webhooks, spins up lightweight k3s sandboxes on AWS EC2, manages Route53 records via custom scripts, and injects HashiCorp Vault secrets directly into pods.",
        results: "Deployment time for dynamic sandbox servers dropped to under 90 seconds. Automated clean-up of idle sandbox instances reduced monthly AWS bills by $8,500.",
        architecture: {
          frontend: "Svelte (Admin portal UI)",
          backend: "Go (Kubernetes Controller)",
          database: "PostgreSQL & HashiCorp Vault"
        },
        tech_stack: {
          frontend: ["HTML5", "CSS3", "JavaScript"],
          backend: ["Go", "Vault API", "Docker SDK"],
          cloud_devops: ["AWS EKS", "Terraform", "ArgoCD", "Kubernetes"]
        },
        code_snippet: `apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-sandbox-sandboxname
  namespace: opsflow-system
spec:
  template:
    spec:
      containers:
      - name: builder
        image: hashicorp/terraform:1.6.0
        command: ["sh", "-c"]
        args:
        - |
          terraform init
          terraform apply -var="sandbox_id=sandboxname" -auto-approve
          kubectl apply -f /app/deployment-manifests/
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key
      restartPolicy: Never`,
        metrics_cards: {
          lighthouse: "97/100",
          load_time: "1.1s",
          api_latency: "< 150ms orchestration"
        }
      }
    }
  },
  articles: {
    "optimizing-frappe-queries": `
# Optimizing database queries in Frappe Framework and ERPNext

When scaling ERPNext to handle millions of transactions, database performance is usually the primary bottleneck. Let's explore how we optimized inventory queries in a high-volume custom Frappe app.

## The Problem
By default, the Frappe ORM processes documents individually. Running \`frappe.get_doc\` or \`frm.save\` in a loop triggers:
1. Multiple SELECT queries to fetch child tables.
2. Individual validation hooks (which might run additional queries).
3. A separate UPDATE/INSERT for each record.

Under high load, this causes massive database lock contention and Gunicorn worker timeouts.

## The Solution: Bulk Query Execution with PyPika
Instead of relying on \`frappe.get_doc\` for bulk updates, we can bypass the ORM and construct safe, parameterized queries using Frappe's built-in PyPika wrapper:

\`\`\`python
import frappe
from pypika import Table, Query

def bulk_update_item_status(item_codes, status):
    # Get a reference to the MariaDB table
    item_table = Table("tabItem")
    
    # Build query
    query = (
        Query.update(item_table)
        .set(item_table.disabled, 1 if status == "Disabled" else 0)
        .where(item_table.item_code.isin(item_codes))
    )
    
    # Execute query
    frappe.db.sql(str(query))
\`\`\`

## Optimizing Indexes
In addition to bulk queries, adding a composite index on frequently searched fields (e.g., \`item_code\` and \`warehouse\` in \`tabStock Ledger Entry\`) can reduce index lookup latency:

\`\`\`sql
CREATE INDEX idx_item_warehouse ON \`tabStock Ledger Entry\` (item_code, warehouse);
\`\`\`

## Performance Metrics
After executing these optimizations:
* **API response times** decreased by **85%**.
* **Database lock wait times** dropped to **zero**.
* **Daily transaction throughput** increased by **300%** without CPU scaling.
    `,
    "scaling-django-apis": `
# Scaling Django APIs to 50k Requests Per Minute

Building REST APIs with Django Rest Framework (DRF) is straightforward, but scaling them to support tens of thousands of requests per minute requires architectural changes.

## 1. Eliminate N+1 Queries
The most common source of API latency is the N+1 query problem, where Django fetches foreign keys in separate queries. Use \`select_related\` (for ForeignKey and OneToOne) and \`prefetch_related\` (for ManyToMany) to fetch all records in a single join query.

\`\`\`python
# Before (Slow)
queryset = Book.objects.all() # Triggers query for author on every iteration

# After (Fast)
queryset = Book.objects.select_related('author').all()
\`\`\`

## 2. Redis Cache Middleware
Implementing an aggressive caching layer for static data or heavy read endpoints can reduce database load:

\`\`\`python
from django.core.cache import cache

def get_dashboard_metrics(request):
    cache_key = "dashboard_metrics_data"
    data = cache.get(cache_key)
    
    if not data:
        data = calculate_heavy_metrics()
        cache.set(cache_key, data, timeout=300) # Cache for 5 mins
        
    return JsonResponse(data)
\`\`\`

## 3. Offloading Work with Celery
Never run time-consuming tasks (like email delivery or pdf generation) in the main request-response cycle. Offload them to background worker processes:

\`\`\`python
# tasks.py
@shared_task
def send_welcome_email(user_id):
    user = User.objects.get(id=user_id)
    send_mail("Welcome!", "Thanks for signing up.", "admin@saas.com", [user.email])
\`\`\`

## Key Results
* Average API Latency: **from 320ms to 45ms**
* CPU Utilization: **Reduced by 55%**
* System Throughput: **Successfully sustained 50k RPM**
    `
  }
};

// Check for custom LocalStorage configuration, merge with default
const PORTFOLIO_CONFIG = JSON.parse(localStorage.getItem('portfolio_config')) || { ...DEFAULT_CONFIG };

// Extract databases
const PROJECTS_DATABASE = PORTFOLIO_CONFIG.projects;
const ARTICLES_DATABASE = PORTFOLIO_CONFIG.articles;

document.addEventListener('DOMContentLoaded', () => {
  // Initialize Lucide Icons
  if (window.lucide) window.lucide.createIcons();

  // Hide loader after page load
  window.addEventListener('load', () => {
    const loader = document.getElementById('loader');
    if (loader) {
      setTimeout(() => {
        loader.style.opacity = '0';
        loader.style.visibility = 'hidden';
        initHeroAnimations();
      }, 1200);
    }
  });

  // Reading progress scroll tracer
  window.addEventListener('scroll', () => {
    const winScroll = document.documentElement.scrollTop || document.body.scrollTop;
    const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
    const scrolled = height > 0 ? (winScroll / height) * 100 : 0;
    const bar = document.getElementById('reading-progress');
    if (bar) bar.style.width = scrolled + '%';
  });

  // Load Dyn Content from config
  loadDynamicElements();

  initSpecialtyRotator();
  initThemeManager();
  setupFilters();
  initCommandPalette();
  initMobileMenu();
  generateGithubCalendar();
  initContactForm();
  initOverlayListeners();
  initScrollAnimations();
});

/* ==========================================================================
   DYNAMIC POPULATION FROM CORE CONFIG
   ========================================================================== */
function loadDynamicElements() {
  const cfg = PORTFOLIO_CONFIG;

  // Populating Hero name and description
  const titleContainer = document.querySelector('.hero-title');
  if (titleContainer) {
    titleContainer.innerHTML = `Building Systems That <span class="gradient-text">Scale.</span>`;
  }
  const subtitleContainer = document.querySelector('.hero-subtitle');
  if (subtitleContainer) {
    subtitleContainer.innerHTML = `I'm <strong>${cfg.hero.name}</strong>, ${cfg.hero.role}. ${cfg.hero.subtitle}`;
  }

  // Populating About Detail Badges
  const detailCards = document.querySelectorAll('.about-detail-card');
  if (detailCards.length >= 4) {
    detailCards[0].querySelector('p').textContent = cfg.hero.location;
    detailCards[1].querySelector('p').textContent = cfg.hero.learning;
    detailCards[2].querySelector('p').textContent = cfg.hero.availability;
    detailCards[3].querySelector('p').textContent = cfg.hero.fun_fact;
  }

  // Populating About Bio Description
  const bioContainer = document.querySelector('.about-info');
  if (bioContainer) {
    const header = bioContainer.querySelector('.about-heading');
    const detailsGrid = bioContainer.querySelector('.about-details-grid');
    const paragraphs = cfg.hero.bio.split('\n\n').map(p => `<p>${p}</p>`).join('');
    
    bioContainer.innerHTML = '';
    if (header) bioContainer.appendChild(header);
    bioContainer.innerHTML += paragraphs;
    if (detailsGrid) bioContainer.appendChild(detailsGrid);
  }

  // Populating Experience Timeline
  const timeline = document.querySelector('.timeline');
  if (timeline) {
    timeline.innerHTML = '';
    cfg.experience.forEach(exp => {
      const item = document.createElement('div');
      item.className = 'timeline-item';
      
      const achievementsList = exp.achievements.map(a => `<li>${a}</li>`).join('');
      const tagsList = exp.tags.split(',').map(t => `<span class="tag">${t.trim()}</span>`).join('');

      item.innerHTML = `
        <div class="timeline-dot"></div>
        <div class="timeline-date">${exp.period}</div>
        <div class="timeline-content">
          <h3 class="timeline-title">${exp.title} <span class="timeline-company">@ ${exp.company}</span></h3>
          <p class="timeline-summary">${exp.summary}</p>
          <ul class="timeline-achievements">
            ${achievementsList}
          </ul>
          <div class="timeline-tags">
            ${tagsList}
          </div>
        </div>
      `;
      timeline.appendChild(item);
    });
  }

  // Populating Skills Matrix
  const skillsMatrix = document.querySelector('.skills-grid');
  if (skillsMatrix) {
    skillsMatrix.innerHTML = '';
    const categories = [
      { key: 'languages', title: 'Languages', icon: 'code' },
      { key: 'frameworks', title: 'Frameworks', icon: 'layers' },
      { key: 'cloud', title: 'DevOps & Cloud', icon: 'cloud' }
    ];

    categories.forEach(cat => {
      const card = document.createElement('div');
      card.className = 'skills-card';
      
      const skillItemsList = cfg.skills[cat.key].map(skill => `
        <div class="skill-item">
          <span class="skill-name">${skill.name}</span>
          <div class="skill-bar-container"><div class="skill-bar" data-width="${skill.value}%"></div></div>
        </div>
      `).join('');

      card.innerHTML = `
        <h3 class="skills-group-title"><i data-lucide="${cat.icon}"></i> ${cat.title}</h3>
        <div class="skill-list">
          ${skillItemsList}
        </div>
      `;
      skillsMatrix.appendChild(card);
    });
    if (window.lucide) window.lucide.createIcons();
  }

  // Populating Projects Grid
  const projectsGrid = document.getElementById('projects-list');
  if (projectsGrid) {
    projectsGrid.innerHTML = '';
    Object.keys(cfg.projects).forEach(key => {
      const proj = cfg.projects[key];
      const card = document.createElement('article');
      card.className = 'project-card';
      card.setAttribute('data-category', proj.category);

      const starsTag = proj.github_stars 
        ? `<span class="project-stars-badge"><i data-lucide="star" style="width:12px;height:12px;"></i> ${proj.github_stars}</span>` 
        : '';
      
      const tagsList = proj.case_study.tech_stack.backend.concat(proj.case_study.tech_stack.frontend).slice(0, 5)
        .map(t => `<span class="tech-tag">${t}</span>`).join('');

      card.innerHTML = `
        <div class="project-card-header">
          <img src="${proj.thumbnail}" alt="${proj.title}" class="project-thumbnail" loading="lazy">
          <span class="project-status-badge">${proj.status}</span>
          ${starsTag}
        </div>
        <div class="project-card-body">
          <h3 class="project-title">${proj.title}</h3>
          <p class="project-summary">${proj.summary}</p>
          <div class="project-tech-tags">
            ${tagsList}
          </div>
          <div class="project-actions">
            <a href="#" class="project-link-btn btn-case-study" data-project-id="${proj.id}">
              Engineering Case Study <i data-lucide="arrow-up-right" style="width:14px;height:14px;"></i>
            </a>
          </div>
        </div>
      `;
      projectsGrid.appendChild(card);
    });
    if (window.lucide) window.lucide.createIcons();
  }

  // Populating Blog Publications
  const blogGrid = document.querySelector('.blog-grid');
  if (blogGrid) {
    blogGrid.innerHTML = '';
    Object.keys(cfg.articles).forEach(key => {
      const md = cfg.articles[key];
      const title = md.split('\n')[0].replace('#', '').trim();
      const card = document.createElement('div');
      card.className = 'blog-card';
      card.setAttribute('data-article-id', key);
      
      const dateString = key === 'optimizing-frappe-queries' ? 'March 12, 2026' : 'February 28, 2026';
      const excerpt = key === 'optimizing-frappe-queries' 
        ? 'A deep dive into MariaDB indexes, batch query optimization, and bypassing the Frappe ORM safely to scale record writes by 85%.' 
        : 'Explore concrete architecture strategies: select_related optimization, Redis-backed key caches, and offloading workload payloads to Celery.';

      card.innerHTML = `
        <span class="blog-date">${dateString}</span>
        <h3 class="blog-card-title">${title}</h3>
        <p class="blog-card-excerpt">${excerpt}</p>
        <span class="blog-read-more">Read Article <i data-lucide="arrow-right"></i></span>
      `;
      blogGrid.appendChild(card);
    });
    if (window.lucide) window.lucide.createIcons();
  }
}

/* ==========================================================================
   HERO ENTRANCE ANIMATIONS
   ========================================================================== */
function initHeroAnimations() {
  if (typeof gsap !== 'undefined') {
    const tl = gsap.timeline();
    tl.from('.hero-badge', { opacity: 0, y: -20, duration: 0.6, ease: 'power2.out' })
      .from('.hero-title', { opacity: 0, y: 30, duration: 0.8, ease: 'power3.out' }, '-=0.4')
      .from('.hero-subtitle', { opacity: 0, y: 20, duration: 0.8, ease: 'power3.out' }, '-=0.6')
      .from('.hero-specialties-container', { opacity: 0, y: 15, duration: 0.6, ease: 'power2.out' }, '-=0.5')
      .from('.hero-ctas .btn', { opacity: 0, y: 20, duration: 0.6, ease: 'power2.out', stagger: 0.15 }, '-=0.4')
      .from('.hero-socials', { opacity: 0, y: 15, duration: 0.5, ease: 'power2.out' }, '-=0.2');
  }
}

/* ==========================================================================
   ROTATING SPECIALTIES
   ========================================================================== */
function initSpecialtyRotator() {
  const specialties = PORTFOLIO_CONFIG.hero.specialties.split(',').map(s => s.trim());
  let currentIndex = 0;
  const targetElement = document.getElementById('rotating-specialty');
  
  if (!targetElement || specialties.length === 0) return;

  setInterval(() => {
    if (typeof gsap !== 'undefined') {
      gsap.to(targetElement, {
        opacity: 0,
        y: -10,
        duration: 0.3,
        onComplete: () => {
          currentIndex = (currentIndex + 1) % specialties.length;
          targetElement.textContent = specialties[currentIndex];
          gsap.to(targetElement, {
            opacity: 1,
            y: 0,
            duration: 0.3
          });
        }
      });
    } else {
      currentIndex = (currentIndex + 1) % specialties.length;
      targetElement.textContent = specialties[currentIndex];
    }
  }, 3000);
}

/* ==========================================================================
   THEME MANAGER
   ========================================================================== */
function initThemeManager() {
  const toggleBtn = document.getElementById('theme-toggle');
  const htmlElement = document.documentElement;

  if (!toggleBtn) return;

  const savedTheme = localStorage.getItem('theme') || 'dark';
  htmlElement.setAttribute('data-theme', savedTheme);

  toggleBtn.addEventListener('click', () => {
    const currentTheme = htmlElement.getAttribute('data-theme');
    const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
    
    htmlElement.setAttribute('data-theme', newTheme);
    localStorage.setItem('theme', newTheme);
  });
}

/* ==========================================================================
   PROJECTS FILTER UTILITY
   ========================================================================== */
function setupFilters() {
  const filterBtns = document.querySelectorAll('.filter-btn');

  filterBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      filterBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');

      const filterVal = btn.getAttribute('data-filter');
      const cards = document.querySelectorAll('.project-card');
      
      if (typeof gsap !== 'undefined') {
        gsap.to('#projects-list', {
          opacity: 0,
          y: 10,
          duration: 0.25,
          onComplete: () => {
            cards.forEach(card => {
              const cardCat = card.getAttribute('data-category');
              if (filterVal === 'all' || cardCat === filterVal) {
                card.style.display = 'flex';
              } else {
                card.style.display = 'none';
              }
            });
            gsap.to('#projects-list', { opacity: 1, y: 0, duration: 0.25 });
          }
        });
      } else {
        cards.forEach(card => {
          const cardCat = card.getAttribute('data-category');
          if (filterVal === 'all' || cardCat === filterVal) {
            card.style.display = 'flex';
          } else {
            card.style.display = 'none';
          }
        });
      }
    });
  });
}

/* ==========================================================================
   CASE STUDY VIEWER
   ========================================================================== */
function openCaseStudy(projId) {
  const project = PROJECTS_DATABASE[projId];
  if (!project) return;

  const csContent = document.getElementById('case-study-content');
  const overlay = document.getElementById('case-study-overlay');
  
  csContent.innerHTML = `
    <div class="case-study-hero">
      <h1 class="case-study-title">${project.title}</h1>
      <div class="case-study-meta-grid">
        <div class="meta-box">
          <span class="meta-label">Timeline</span>
          <span class="meta-val">${project.case_study.timeline}</span>
        </div>
        <div class="meta-box">
          <span class="meta-label">Role</span>
          <span class="meta-val">${project.case_study.role}</span>
        </div>
        <div class="meta-box">
          <span class="meta-label">Client</span>
          <span class="meta-val">${project.case_study.client}</span>
        </div>
        <div class="meta-box">
          <span class="meta-label">Team Size</span>
          <span class="meta-val">${project.case_study.team_size}</span>
        </div>
      </div>
    </div>

    <div class="case-study-body">
      <div class="case-study-main">
        <section class="case-study-section">
          <h2 class="case-study-section-title">Project Overview</h2>
          <p><strong>Problem Statement:</strong> ${project.case_study.problem}</p>
          <p><strong>Business Requirements:</strong> ${project.case_study.requirements}</p>
        </section>

        <section class="case-study-section">
          <h2 class="case-study-section-title">Architectural Implementation</h2>
          <p>${project.case_study.solution}</p>
          <div class="architecture-container">
            <h4>System Block Diagram</h4>
            <div class="arch-diagram-grid" style="margin-top:20px;">
              <div class="arch-node active">
                <strong>Frontend Client</strong>
                <p style="font-size:11px;margin:0;color:var(--text-secondary);">${project.case_study.architecture.frontend}</p>
              </div>
              <div class="arch-arrow">↓ API Calls / WebSocket Streams</div>
              <div class="arch-node active">
                <strong>Application Gateway / Backend Core</strong>
                <p style="font-size:11px;margin:0;color:var(--text-secondary);">${project.case_study.architecture.backend}</p>
              </div>
              <div class="arch-arrow">↓ Cache & Persistence Queries</div>
              <div class="arch-node active">
                <strong>Database & Cache Layers</strong>
                <p style="font-size:11px;margin:0;color:var(--text-secondary);">${project.case_study.architecture.database}</p>
              </div>
            </div>
          </div>
        </section>

        <section class="case-study-section">
          <h2 class="case-study-section-title">Code Showcase & Optimization</h2>
          <p>The core logic uses optimized processing and clean abstractions:</p>
          <div class="code-container">
            <div class="code-header">
              <span class="code-lang">Source Code</span>
              <button class="code-copy-btn" onclick="copyCodeSnippet(this)"><i data-lucide="copy" style="width:12px;height:12px;"></i> Copy Code</button>
            </div>
            <pre class="code-block" id="cs-code-snippet">${escapeHtml(project.case_study.code_snippet)}</pre>
          </div>
        </section>

        <section class="case-study-section">
          <h2 class="case-study-section-title">Challenges & Critical Debugging</h2>
          <p>${project.case_study.challenges}</p>
        </section>
      </div>

      <div class="case-study-sidebar">
        <section class="case-study-section">
          <h2 class="case-study-section-title">Performance Metrics</h2>
          <div class="metrics-grid">
            <div class="metric-card">
              <span class="metric-card-val">${project.case_study.metrics_cards.load_time}</span>
              <span class="metric-card-lbl">Load Time</span>
            </div>
            <div class="metric-card">
              <span class="metric-card-val">${project.case_study.metrics_cards.api_latency}</span>
              <span class="metric-card-lbl">API Latency</span>
            </div>
            <div class="metric-card" style="grid-column: span 2;">
              <span class="metric-card-val" style="color:var(--accent-color);">${project.case_study.metrics_cards.lighthouse}</span>
              <span class="metric-card-lbl">Lighthouse / Health Index</span>
            </div>
          </div>
        </section>

        <section class="case-study-section">
          <h2 class="case-study-section-title">Tech Stack Used</h2>
          <div style="display:flex; flex-direction:column; gap:16px;">
            <div>
              <h5 style="margin-bottom:8px;font-size:12px;color:var(--text-muted);">BACKEND</h5>
              <div style="display:flex; flex-wrap:wrap; gap:6px;">
                ${project.case_study.tech_stack.backend.map(t => `<span class="tech-tag">${t}</span>`).join('')}
              </div>
            </div>
            <div>
              <h5 style="margin-bottom:8px;font-size:12px;color:var(--text-muted);">FRONTEND</h5>
              <div style="display:flex; flex-wrap:wrap; gap:6px;">
                ${project.case_study.tech_stack.frontend.map(t => `<span class="tech-tag">${t}</span>`).join('')}
              </div>
            </div>
            <div>
              <h5 style="margin-bottom:8px;font-size:12px;color:var(--text-muted);">CLOUD & INFRASTRUCTURE</h5>
              <div style="display:flex; flex-wrap:wrap; gap:6px;">
                ${project.case_study.tech_stack.cloud_devops.map(t => `<span class="tech-tag">${t}</span>`).join('')}
              </div>
            </div>
          </div>
        </section>

        <section class="case-study-section" style="margin-top:40px;">
          <a href="${project.case_study.github_repo}" target="_blank" class="btn btn-secondary" style="width:100%;margin-bottom:12px;justify-content:center;">
            <i data-lucide="github"></i> View Repository
          </a>
        </section>
      </div>
    </div>
  `;

  if (window.lucide) window.lucide.createIcons();

  overlay.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

window.copyCodeSnippet = (btn) => {
  const codeBlock = document.getElementById('cs-code-snippet');
  if (!codeBlock) return;
  
  navigator.clipboard.writeText(codeBlock.innerText).then(() => {
    btn.innerHTML = `<i data-lucide="check" style="width:12px;height:12px;color:var(--success-color);"></i> Copied!`;
    if (window.lucide) window.lucide.createIcons();
    setTimeout(() => {
      btn.innerHTML = `<i data-lucide="copy" style="width:12px;height:12px;"></i> Copy Code`;
      if (window.lucide) window.lucide.createIcons();
    }, 2000);
  });
};

/* ==========================================================================
   BLOG READER
   ========================================================================== */
function openBlogArticle(articleId) {
  const overlay = document.getElementById('case-study-overlay');
  const contentContainer = document.getElementById('case-study-content');
  const markdownText = ARTICLES_DATABASE[articleId];

  if (!markdownText) return;
  
  let parsedHtml = '';
  if (typeof marked !== 'undefined') {
    parsedHtml = window.marked.parse(markdownText);
  } else {
    parsedHtml = `<pre>${markdownText}</pre>`;
  }
  
  contentContainer.innerHTML = `
    <div class="blog-content">
      <span class="blog-meta"><i data-lucide="book-open" style="width:14px;height:14px;display:inline-block;vertical-align:middle;margin-right:4px;"></i> Technical Article / Architecture Guide</span>
      <div class="blog-body-text">${parsedHtml}</div>
    </div>
  `;
  
  if (window.lucide) window.lucide.createIcons();
  
  overlay.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function initOverlayListeners() {
  const closeBtn = document.getElementById('case-study-close');
  const overlay = document.getElementById('case-study-overlay');

  if (closeBtn && overlay) {
    closeBtn.addEventListener('click', () => {
      overlay.classList.remove('open');
      document.body.style.overflow = '';
    });
  }

  // Set delegate click on dynamically created study links
  document.addEventListener('click', (e) => {
    const target = e.target.closest('.btn-case-study');
    if (target) {
      e.preventDefault();
      const projId = target.getAttribute('data-project-id');
      openCaseStudy(projId);
    }

    const blogCard = e.target.closest('.blog-card');
    if (blogCard) {
      const articleId = blogCard.getAttribute('data-article-id');
      openBlogArticle(articleId);
    }
  });
}

/* ==========================================================================
   COMMAND PALETTE
   ========================================================================== */
function initCommandPalette() {
  const palette = document.getElementById('command-palette');
  const searchInput = document.getElementById('palette-search-input');
  const resultsContainer = document.getElementById('palette-results-list');
  const toggleBtn = document.getElementById('palette-toggle');

  if (!palette || !searchInput || !resultsContainer) return;

  const items = [
    { name: 'View Projects list', action: 'scroll:#projects', shortcut: 'G P', icon: 'folder' },
    { name: 'View Technical Skills', action: 'scroll:#skills', shortcut: 'G S', icon: 'code-2' },
    { name: 'View Work Experience', action: 'scroll:#experience', shortcut: 'G E', icon: 'briefcase' },
    { name: 'Open Interactive CLI Terminal', action: 'terminal', shortcut: '`', icon: 'terminal' },
    { name: 'Launch Bug Hunt Debugger', action: 'playground:bug-hunt', shortcut: 'P B', icon: 'bug' },
    { name: 'Open API Playground', action: 'playground:api-playground', shortcut: 'P A', icon: 'globe' },
    { name: 'Open Mini ERP Workspace', action: 'playground:erp-sandbox', shortcut: 'P E', icon: 'layout' },
    { name: 'Download PDF Resume', action: 'download:assets/resume.pdf', shortcut: 'R', icon: 'download' },
    { name: 'Visit Developer GitHub', action: 'github', shortcut: 'G H', icon: 'github' },
    { name: 'Contact Developer', action: 'scroll:#contact', shortcut: 'G C', icon: 'mail' },
    { name: 'Toggle UI Theme', action: 'theme', shortcut: 'T', icon: 'sun' },
    { name: 'Toggle Developer Mode', action: 'devmode', shortcut: 'D M', icon: 'settings' }
  ];

  let selectedIndex = 0;
  let filteredItems = [...items];

  function togglePalette() {
    const isOpen = palette.classList.toggle('open');
    if (isOpen) {
      if (window.unlockAchievement) {
        window.unlockAchievement('keyboard-ninja');
      }
      searchInput.value = '';
      selectedIndex = 0;
      renderItems(items);
      setTimeout(() => searchInput.focus(), 50);
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
  }

  function renderItems(list) {
    resultsContainer.innerHTML = '';
    list.forEach((item, index) => {
      const el = document.createElement('div');
      el.className = `palette-item ${index === selectedIndex ? 'selected' : ''}`;
      el.innerHTML = `
        <i data-lucide="${item.icon}" class="palette-item-icon" style="width:16px;height:16px;"></i>
        <span class="palette-item-text">${item.name}</span>
        <span class="palette-item-shortcut">${item.shortcut}</span>
      `;
      
      el.addEventListener('click', () => executeAction(item.action));
      resultsContainer.appendChild(el);
    });
    if (window.lucide) window.lucide.createIcons();
  }

  function executeAction(action) {
    togglePalette();
    if (action.startsWith('scroll:')) {
      const selector = action.split(':')[1];
      const el = document.querySelector(selector);
      if (el) el.scrollIntoView({ behavior: 'smooth' });
    } else if (action === 'theme') {
      const toggle = document.getElementById('theme-toggle');
      if (toggle) toggle.click();
    } else if (action === 'terminal') {
      const toggle = document.getElementById('terminal-toggle');
      if (toggle) toggle.click();
    } else if (action.startsWith('download:')) {
      const path = action.split(':')[1];
      const link = document.createElement('a');
      link.href = path;
      link.download = 'Alex_Carter_Resume.pdf';
      link.click();
    } else if (action.startsWith('playground:')) {
      const tabName = action.split(':')[1];
      const el = document.querySelector('#playground');
      if (el) el.scrollIntoView({ behavior: 'smooth' });
      const tabBtn = document.querySelector(`.playground-tab[data-tab="${tabName}"]`);
      if (tabBtn) tabBtn.click();
    } else if (action === 'github') {
      window.open('https://github.com', '_blank');
    } else if (action === 'devmode') {
      const devModeBtn = document.getElementById('devmode-toggle-btn');
      if (devModeBtn) devModeBtn.click();
    }
  }

  window.addEventListener('keydown', (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') {
      e.preventDefault();
      togglePalette();
    }
    
    if (e.key === 'Escape' && palette.classList.contains('open')) {
      togglePalette();
    }
  });

  if (toggleBtn) toggleBtn.addEventListener('click', togglePalette);

  searchInput.addEventListener('input', (e) => {
    const val = e.target.value.toLowerCase();
    filteredItems = items.filter(item => item.name.toLowerCase().includes(val));
    selectedIndex = 0;
    renderItems(filteredItems);
  });

  searchInput.addEventListener('keydown', (e) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      selectedIndex = (selectedIndex + 1) % filteredItems.length;
      renderItems(filteredItems);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      selectedIndex = (selectedIndex - 1 + filteredItems.length) % filteredItems.length;
      renderItems(filteredItems);
    } else if (e.key === 'Enter') {
      e.preventDefault();
      if (filteredItems[selectedIndex]) {
        executeAction(filteredItems[selectedIndex].action);
      }
    }
  });
}

/* ==========================================================================
   MOBILE MENU MANAGER
   ========================================================================== */
function initMobileMenu() {
  const toggle = document.querySelector('.mobile-nav-toggle');
  const overlay = document.querySelector('.mobile-menu-overlay');
  
  if (!toggle || !overlay) return;

  toggle.addEventListener('click', () => {
    const isOpen = overlay.classList.toggle('open');
    toggle.innerHTML = isOpen ? `<i data-lucide="x"></i>` : `<i data-lucide="menu"></i>`;
    if (window.lucide) window.lucide.createIcons();
    document.body.style.overflow = isOpen ? 'hidden' : '';
  });

  document.querySelectorAll('.mobile-item').forEach(item => {
    item.addEventListener('click', () => {
      overlay.classList.remove('open');
      toggle.innerHTML = `<i data-lucide="menu"></i>`;
      if (window.lucide) window.lucide.createIcons();
      document.body.style.overflow = '';
    });
  });
}

/* ==========================================================================
   MOCK GITHUB CALENDAR
   ========================================================================== */
function generateGithubCalendar() {
  const calendar = document.getElementById('github-calendar-grid');
  if (!calendar) return;

  for (let i = 0; i < 168; i++) {
    const day = document.createElement('div');
    const rand = Math.random();
    let level = 0;
    if (rand > 0.85) level = 4;
    else if (rand > 0.7) level = 3;
    else if (rand > 0.5) level = 2;
    else if (rand > 0.25) level = 1;
    
    day.className = `calendar-day level-${level}`;
    calendar.appendChild(day);
  }
}

/* ==========================================================================
   CONTACT FORM SUBMISSION
   ========================================================================== */
function initContactForm() {
  const form = document.getElementById('contact-form');
  const feedback = document.getElementById('form-feedback');

  if (!form || !feedback) return;

  form.addEventListener('submit', (e) => {
    e.preventDefault();
    
    const submitBtn = form.querySelector('.form-submit-btn');
    const originalText = submitBtn.innerHTML;
    submitBtn.innerHTML = `Sending... <span class="loader-spinner" style="width:14px;height:14px;display:inline-block;border-width:2px;margin-left:6px;"></span>`;
    submitBtn.disabled = true;

    setTimeout(() => {
      submitBtn.innerHTML = originalText;
      submitBtn.disabled = false;
      feedback.textContent = "Message sent successfully! Alex will get back to you shortly.";
      feedback.className = "form-feedback success";
      form.reset();

      setTimeout(() => {
        feedback.className = "form-feedback";
      }, 5000);
    }, 1500);
  });
}

/* ==========================================================================
   GSAP SCROLL TRIGGER ANIMATIONS
   ========================================================================== */
function initScrollAnimations() {
  if (typeof gsap === 'undefined' || typeof ScrollTrigger === 'undefined') return;

  gsap.registerPlugin(ScrollTrigger);

  document.querySelectorAll('.section-title').forEach(title => {
    gsap.from(title, {
      scrollTrigger: {
        trigger: title,
        start: 'top 85%'
      },
      opacity: 0,
      x: -30,
      duration: 0.8,
      ease: 'power2.out'
    });
  });

  gsap.utils.toArray('.skill-bar').forEach(bar => {
    const targetWidth = bar.getAttribute('data-width');
    gsap.to(bar, {
      scrollTrigger: {
        trigger: bar,
        start: 'top 90%'
      },
      width: targetWidth,
      duration: 1.5,
      ease: 'power3.out'
    });
  });
}
